/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellAdminRouteImport } from './routes/_shell/admin'
import { Route as ShellContainersRouteImport } from './routes/_shell/containers'
import { Route as ShellDeploymentsRouteImport } from './routes/_shell/deployments'
import { Route as ShellNotificationsRouteImport } from './routes/_shell/notifications'
import { Route as ShellLogsDeploymentIdRouteImport } from './routes/_shell/logs.$deploymentId'
import { Route as ShellProjectsProjectIdRouteImport } from './routes/_shell/projects.$projectId'
import { Route as ShellProjectsNewRouteImport } from './routes/_shell/projects.new'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdminRoute = ShellAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ShellRoute,
} as any)
const ShellContainersRoute = ShellContainersRouteImport.update({
  id: '/containers',
  path: '/containers',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDeploymentsRoute = ShellDeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => ShellRoute,
} as any)
const ShellNotificationsRoute = ShellNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLogsDeploymentIdRoute = ShellLogsDeploymentIdRouteImport.update({
  id: '/logs/$deploymentId',
  path: '/logs/$deploymentId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProjectsProjectIdRoute = ShellProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProjectsNewRoute = ShellProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof ShellAdminRoute
  '/containers': typeof ShellContainersRoute
  '/deployments': typeof ShellDeploymentsRoute
  '/notifications': typeof ShellNotificationsRoute
  '/logs/$deploymentId': typeof ShellLogsDeploymentIdRoute
  '/projects/$projectId': typeof ShellProjectsProjectIdRoute
  '/projects/new': typeof ShellProjectsNewRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/admin': typeof ShellAdminRoute
  '/containers': typeof ShellContainersRoute
  '/deployments': typeof ShellDeploymentsRoute
  '/notifications': typeof ShellNotificationsRoute
  '/': typeof ShellIndexRoute
  '/logs/$deploymentId': typeof ShellLogsDeploymentIdRoute
  '/projects/$projectId': typeof ShellProjectsProjectIdRoute
  '/projects/new': typeof ShellProjectsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/_shell/admin': typeof ShellAdminRoute
  '/_shell/containers': typeof ShellContainersRoute
  '/_shell/deployments': typeof ShellDeploymentsRoute
  '/_shell/notifications': typeof ShellNotificationsRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/logs/$deploymentId': typeof ShellLogsDeploymentIdRoute
  '/_shell/projects/$projectId': typeof ShellProjectsProjectIdRoute
  '/_shell/projects/new': typeof ShellProjectsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/containers'
    | '/deployments'
    | '/notifications'
    | '/logs/$deploymentId'
    | '/projects/$projectId'
    | '/projects/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/admin'
    | '/containers'
    | '/deployments'
    | '/notifications'
    | '/'
    | '/logs/$deploymentId'
    | '/projects/$projectId'
    | '/projects/new'
  id:
    | '__root__'
    | '/_shell'
    | '/login'
    | '/_shell/admin'
    | '/_shell/containers'
    | '/_shell/deployments'
    | '/_shell/notifications'
    | '/_shell/'
    | '/_shell/logs/$deploymentId'
    | '/_shell/projects/$projectId'
    | '/_shell/projects/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admin': {
      id: '/_shell/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ShellAdminRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/containers': {
      id: '/_shell/containers'
      path: '/containers'
      fullPath: '/containers'
      preLoaderRoute: typeof ShellContainersRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/deployments': {
      id: '/_shell/deployments'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof ShellDeploymentsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/notifications': {
      id: '/_shell/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof ShellNotificationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/logs/$deploymentId': {
      id: '/_shell/logs/$deploymentId'
      path: '/logs/$deploymentId'
      fullPath: '/logs/$deploymentId'
      preLoaderRoute: typeof ShellLogsDeploymentIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/projects/$projectId': {
      id: '/_shell/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ShellProjectsProjectIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/projects/new': {
      id: '/_shell/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ShellProjectsNewRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAdminRoute: typeof ShellAdminRoute
  ShellContainersRoute: typeof ShellContainersRoute
  ShellDeploymentsRoute: typeof ShellDeploymentsRoute
  ShellNotificationsRoute: typeof ShellNotificationsRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellLogsDeploymentIdRoute: typeof ShellLogsDeploymentIdRoute
  ShellProjectsProjectIdRoute: typeof ShellProjectsProjectIdRoute
  ShellProjectsNewRoute: typeof ShellProjectsNewRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAdminRoute: ShellAdminRoute,
  ShellContainersRoute: ShellContainersRoute,
  ShellDeploymentsRoute: ShellDeploymentsRoute,
  ShellNotificationsRoute: ShellNotificationsRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellLogsDeploymentIdRoute: ShellLogsDeploymentIdRoute,
  ShellProjectsProjectIdRoute: ShellProjectsProjectIdRoute,
  ShellProjectsNewRoute: ShellProjectsNewRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
